export const GET_DATA_JOB_DETAIL = 'GET_DATA_JOB_DETAIL';
export const GET_DATA_JOB_DETAIL_SUCCESS = 'GET_DATA_JOB_DETAIL_SUCCESS';
export const GET_DATA_JOB_DETAIL_ERROR = 'GET_DATA_JOB_DETAIL_ERROR';
export const RESET_DATA_JOB_DETAIL = 'RESET_DATA_JOB_DETAIL';