export const GET_DATA_JOB_LIST = 'GET_DATA_JOB_LIST';
export const GET_DATA_JOB_LIST_SUCCESS = 'GET_DATA_JOB_LIST_SUCCESS';
export const GET_DATA_JOB_LIST_ERROR = 'GET_DATA_JOB_LIST_ERROR';
export const RESET_DATA_JOB_LIST = 'RESET_DATA_JOB_LIST';