import Head from 'next/head'
import LoginButton from '../components/atoms/ButtonLogin'
import styles from '../styles/Home.module.css'
import Cookies from 'js-cookie'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const isLoggedIn = Cookies.get('isLoggedIn') === 'true'
  if (isLoggedIn) {
    router.push('/job-list')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Job List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <br /> <a href="">Joblist App</a>
        </h1>
        <LoginButton />
      </main>
    </div>
  )
}
